### ISSUE TITLE
The latest 2.0.1 version of Ancient Emipre: Strike Back is FUNDAMENTALLY WORSE than the previous version!!! PLEASE bring back 1.9.5!!!

### ISSUE THREAD

**Issue by ytxmobile98** [theruralriver/theruralriver.github.io#5]
It comes to my attention (and surprise) that this game has an 2.0.1 update after staying at 1.9.5 _for 8 years_. Having full of anticipation about the new features that would come up, I updated the game in Google Play. But… OMG **This is really the only time that I have _regretted_ myself so much for trying the new game.**

Here are the reasons I found the newest **2.0.1** version to be **FUNDAMENTALLY WORSE** than previous versions:

## 1. **Animations**

The popup animations are so **sluggish** now, taking much longer time to load (launching the game / in-game dialogs / end of turn / etc.). Meanwhile, _the unit animations and house smokes are always there and cannot be turned off_. When I played on my phone, it generates a lot of **excessive heat** that I had never experienced when playing prior versions.

## 2. **Settings**

**Are you kidding me???** _What is the point to just have a switch between English and Russian in the game settings?_

I recall that in the past versions there are switches to tweak the **music**, **sound effects**, **unit animations**, **house smokes**, **game difficulty**, **game speed**, etc., _but now these items are now all **gone**_.

### A. Game control

The game control is made **much worse** than in previous versions, including but not limited to:

* **End of turn** _always_ has a confirmation popup and cannot be disabled.
* **Moving an injured unit** back to its base castle now requires _two clicks_, instead of one as in previous versions of the game.
* **Autosaved games** are no longer distinguishable between each other. In the previous version the autosaved games are labeled by the game modes: **Mission auto save**, **Skirmish auto save**, and **User map auto save**. But in 2.0.1 the autosaved games _only contain a word **autosave** followed by the timestamp and the step count_, which is quite useless for me to identify which game was the one I would like to pick up and continue playing.

### B. Money
   
In the new 2.0.1 version each **castle** yields only **$30** each turn ($50 in previous versions, and in the Java version), and each **house** yields only **$20** each turn ($30 in previous versions, and in the Java version). _But how can the price of the troops still remain the same given that the income in each turn is substantially reduced?_ This is the _most significant disruption_ to the **game balance** that has been established since the era of Java version which many players have known about and adapted to _for decades_. When one gets to levels 6~8 where he / she must fight against the enormous enemy army using limited supply of money and troops, it would really be a **DISASTER** for the player to cope with the enemy, especially if they are very close to the player's base.

### C. Units
   
The game mechanics for _several units_ have changed. For example, **Archers** and **Catapults** can fire back at the unit attacking from a distance; **Dire Wolves** can now apply poison when they bite back the attacker. _What is the exact gain of making this alteration which was never present in prior versions, or even in the Java version?_ From my perspective this has **no benefits** for _any player_ **AT ALL** because it would cost much more units on average to take down the enemies' most powerful attack forces. Combined with the previously mentioned lowered income each turn, these changes altogether make up the game that is of **BRUTAL difficulty** for players.

## IMO: The 2.0.1 update is the most DISASTROUS update to the game I have ever experienced.

I saw the 2.0.1 update initially in Google Play, with full of surprise and anticipations. But what does it give me? _It is really a **shame** for this update, which makes the gameplay more **sluggish**, **disruptive** and **difficult**, to be released in Google Play, to all players like me staying tuned to look for new surprises from the game._

**Comment by webbestmaster** [comment]
Hi Tianxing Yang

Thank you for your email. Really, thank you.

1 - I try to fix everything you described, your explanation is good enough.
2 - You can download 1.9.5 apk file, you should remove 2.0.1 and install
1.9.5 -
link to download
https://github.com/theruralriver/theruralriver.github.io/raw/main/45.apk
3 - about languages - if you want you can help me with it. I mean you can
translate the game to your native language (or another language that you
know). I Will send you translate-file for your changes if you want\can\able
to do it.
4 - just one silly question - Where are you? I mean in which country you
live and maybe you use VPN? I just want to test google deploy system.

BR :)

**Comment by ytxmobile98** [comment]
Hi,

I live in China and I have to use VPN to get onto Google, YouTube, Facebook, Twitter, etc. When I use a VPN it may give me an IP from Japan / Singapore / US / UK / France / Netherlands / etc.

I am aware that websites may impose restrictions to the funcionalities when I use a VPN to access them.

**Comment by webbestmaster** [comment]
hi

I hope you installed this and all works as needed (https://github.com/theruralriver/theruralriver.github.io/raw/main/45.apk)


also, I understand that I am responsible to the players and the history of the game

that I succeeded in fixing yesterday:

1 - "Moving an injured unit back to its base castle now requires two clicks, instead of one as in previous versions of the game." - fixed, right now NO need extra click

2 - Archers and Catapults can fire back at the unit attacking from a distance - fixed

3 - Dire Wolves can now apply poison when they bite back the attacker - fixed

4 - In the new 2.0.1 version each castle yields only $30 each turn ($50 in previous versions, and in the Java version), and each house yields only $20 each turn ($30 in previous versions, and in the Java version) - fixed

BR

**Comment by ytxmobile98** [comment]
And what happened to the original repo https://github.com/webbestmaster/main?

**Comment by webbestmaster** [comment]
If you want the AE2 folder - just text me, I will send you a .zip

**Comment by ytxmobile98** [comment]
> If you want the AE2 folder - just text me, I will send you a .zip

Oh thanks. But I have forked it for backup two years ago: https://github.com/ancient-empires/webbestmaster-main-backup

**Comment by ytxmobile98** [comment]
And from my perspective, these aspects of changes are the once that cause unnecessary inconvenience for players, compared to the 1.9.5 version:

1. **Popup animations**: should not be this sluggish. And they also should be dismissible by tapping on the blank areas on the screen rather than by hitting the buttons.
2. **Game difficulty**: should be adjustable by player.
3. **Game speed**: should be adjustable by player. _The current game speed is too slow compared to 1.9.5 version._

**Comment by webbestmaster** [comment]
1 - Some of your perspective already done.
2 - Something will be improved or fixed, I still not decide which one of them.
3 - I am not able to promise something, but I try to do better user experience.
4 - Thank for your opinion and good luck :)

**Comment by webbestmaster** [comment]
Hi

I have done all, except bot level (easy\normal\hard).

Update will be available in 2-3 days.

Thank for your feedback, you made this game little better :)

BR :)

UPD: updated on google play store
