### ISSUE TITLE
[BUG] Catapult MISSING in the initial setup of Level 8 (Heaven's Fury)

### ISSUE THREAD

**Issue by ytxmobile98** [theruralriver/theruralriver.github.io#6]
I recall that in the original versions of the game, the player was given a **Catapult** for free to start with. But in the updated game it's gone.

## Latest version: No catapult

The cursor shows where the Catapult should supposedly be located.

![Screenshot_20230520_160702](https://github.com/theruralriver/theruralriver.github.io/assets/5900105/8f76f127-9607-4eb0-8cab-c39cebcef3d3)

## Previous version: There was a catapult underneath the Golem to start with

![Screenshot from 2023-05-20 16-12-23](https://github.com/theruralriver/theruralriver.github.io/assets/5900105/5de93c51-e2db-4cbe-a812-52c010ccdd47)

**Comment by webbestmaster** [comment]
Hi %username% :)

thank for your issue, I will check it and update\fix it (if need) in several days (about 5-7 day)

BR

**Comment by webbestmaster** [comment]
Catapult has been added. 

Wait for new update on google play.

Thank for your issue one more time :)

BR

**Comment by webbestmaster** [comment]
Google play app has been updated, please check update.

BR
